# LICENSEURI https://yuruna.link/license
# Copyright (c) 2019-2026 by Alisson Sol et al.
# Resources information - aws
---
globalVariables:
  namespace:             "yrn42website-ns"
  clusterDnsPrefix:      "yrn42website-dns"
  resourceGroup:         "yrn42website-rg"
  # regions: aws ec2 describe-regions --query 'Regions[].RegionName' --output text
  resourceRegion:        "us-east-1"
  resourceTags:          "yrn42website-tags"
  registryName:          "componentsRegistry"
  # https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
  clusterVersion:        "1.36"
  nodeType:              "m5.large"
  nodeCount:             3

resources:
# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
- name:                  "componentsRegistry"
  template:              "aws/registry"
  variables:
    # TO-SET: registry name must be globally unique
    uniqueName:          "yrn42registry"

# cluster reference
- name:                  "yrn42website-aws"
  template:              "aws/eks-cluster"
  variables:
    clusterName:         "yrn42website-cluster"
    destinationContext:  "yrn42website-aws"
    nodeResourceGroup:   "${env:resourceGroup}-eks"
