# Copyright (c) 2019-2026 by Alisson Sol et al.
apiVersion: v2
name: yrn42text-to-sql-ui-uxname
description: ASP.NET Core text-to-SQL UI container deployed to a Kubernetes cluster.

type: application
version: 2026.05.29
appVersion: 2026.05.29
icon: https://github.com/cncf/artwork/blob/master/projects/helm/icon/color/helm-icon-color.svg
